# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucy/git/aee

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucy/git/aee

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucy/git/aee/CMakeFiles /home/lucy/git/aee//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucy/git/aee/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aee

# Build rule for target.
aee: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aee
.PHONY : aee

# fast build rule for target.
aee/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/build
.PHONY : aee/fast

#=============================================================================
# Target rules for targets named cjson

# Build rule for target.
cjson: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cjson
.PHONY : cjson

# fast build rule for target.
cjson/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/CMakeFiles/cjson.dir/build.make third_party/cJSON/CMakeFiles/cjson.dir/build
.PHONY : cjson/fast

#=============================================================================
# Target rules for targets named cJSON_test

# Build rule for target.
cJSON_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cJSON_test
.PHONY : cJSON_test

# fast build rule for target.
cJSON_test/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/CMakeFiles/cJSON_test.dir/build.make third_party/cJSON/CMakeFiles/cJSON_test.dir/build
.PHONY : cJSON_test/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/CMakeFiles/check.dir/build.make third_party/cJSON/CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/CMakeFiles/uninstall.dir/build.make third_party/cJSON/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named unity

# Build rule for target.
unity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unity
.PHONY : unity

# fast build rule for target.
unity/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/unity.dir/build.make third_party/cJSON/tests/CMakeFiles/unity.dir/build
.PHONY : unity/fast

#=============================================================================
# Target rules for targets named parse_examples

# Build rule for target.
parse_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parse_examples
.PHONY : parse_examples

# fast build rule for target.
parse_examples/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/parse_examples.dir/build.make third_party/cJSON/tests/CMakeFiles/parse_examples.dir/build
.PHONY : parse_examples/fast

#=============================================================================
# Target rules for targets named parse_number

# Build rule for target.
parse_number: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parse_number
.PHONY : parse_number

# fast build rule for target.
parse_number/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/parse_number.dir/build.make third_party/cJSON/tests/CMakeFiles/parse_number.dir/build
.PHONY : parse_number/fast

#=============================================================================
# Target rules for targets named parse_hex4

# Build rule for target.
parse_hex4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parse_hex4
.PHONY : parse_hex4

# fast build rule for target.
parse_hex4/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/parse_hex4.dir/build.make third_party/cJSON/tests/CMakeFiles/parse_hex4.dir/build
.PHONY : parse_hex4/fast

#=============================================================================
# Target rules for targets named parse_string

# Build rule for target.
parse_string: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parse_string
.PHONY : parse_string

# fast build rule for target.
parse_string/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/parse_string.dir/build.make third_party/cJSON/tests/CMakeFiles/parse_string.dir/build
.PHONY : parse_string/fast

#=============================================================================
# Target rules for targets named parse_array

# Build rule for target.
parse_array: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parse_array
.PHONY : parse_array

# fast build rule for target.
parse_array/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/parse_array.dir/build.make third_party/cJSON/tests/CMakeFiles/parse_array.dir/build
.PHONY : parse_array/fast

#=============================================================================
# Target rules for targets named parse_object

# Build rule for target.
parse_object: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parse_object
.PHONY : parse_object

# fast build rule for target.
parse_object/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/parse_object.dir/build.make third_party/cJSON/tests/CMakeFiles/parse_object.dir/build
.PHONY : parse_object/fast

#=============================================================================
# Target rules for targets named parse_value

# Build rule for target.
parse_value: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parse_value
.PHONY : parse_value

# fast build rule for target.
parse_value/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/parse_value.dir/build.make third_party/cJSON/tests/CMakeFiles/parse_value.dir/build
.PHONY : parse_value/fast

#=============================================================================
# Target rules for targets named print_string

# Build rule for target.
print_string: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 print_string
.PHONY : print_string

# fast build rule for target.
print_string/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/print_string.dir/build.make third_party/cJSON/tests/CMakeFiles/print_string.dir/build
.PHONY : print_string/fast

#=============================================================================
# Target rules for targets named print_number

# Build rule for target.
print_number: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 print_number
.PHONY : print_number

# fast build rule for target.
print_number/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/print_number.dir/build.make third_party/cJSON/tests/CMakeFiles/print_number.dir/build
.PHONY : print_number/fast

#=============================================================================
# Target rules for targets named print_array

# Build rule for target.
print_array: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 print_array
.PHONY : print_array

# fast build rule for target.
print_array/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/print_array.dir/build.make third_party/cJSON/tests/CMakeFiles/print_array.dir/build
.PHONY : print_array/fast

#=============================================================================
# Target rules for targets named print_object

# Build rule for target.
print_object: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 print_object
.PHONY : print_object

# fast build rule for target.
print_object/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/print_object.dir/build.make third_party/cJSON/tests/CMakeFiles/print_object.dir/build
.PHONY : print_object/fast

#=============================================================================
# Target rules for targets named print_value

# Build rule for target.
print_value: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 print_value
.PHONY : print_value

# fast build rule for target.
print_value/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/print_value.dir/build.make third_party/cJSON/tests/CMakeFiles/print_value.dir/build
.PHONY : print_value/fast

#=============================================================================
# Target rules for targets named misc_tests

# Build rule for target.
misc_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 misc_tests
.PHONY : misc_tests

# fast build rule for target.
misc_tests/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/misc_tests.dir/build.make third_party/cJSON/tests/CMakeFiles/misc_tests.dir/build
.PHONY : misc_tests/fast

#=============================================================================
# Target rules for targets named parse_with_opts

# Build rule for target.
parse_with_opts: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parse_with_opts
.PHONY : parse_with_opts

# fast build rule for target.
parse_with_opts/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/parse_with_opts.dir/build.make third_party/cJSON/tests/CMakeFiles/parse_with_opts.dir/build
.PHONY : parse_with_opts/fast

#=============================================================================
# Target rules for targets named compare_tests

# Build rule for target.
compare_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compare_tests
.PHONY : compare_tests

# fast build rule for target.
compare_tests/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/compare_tests.dir/build.make third_party/cJSON/tests/CMakeFiles/compare_tests.dir/build
.PHONY : compare_tests/fast

#=============================================================================
# Target rules for targets named cjson_add

# Build rule for target.
cjson_add: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cjson_add
.PHONY : cjson_add

# fast build rule for target.
cjson_add/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/cjson_add.dir/build.make third_party/cJSON/tests/CMakeFiles/cjson_add.dir/build
.PHONY : cjson_add/fast

#=============================================================================
# Target rules for targets named readme_examples

# Build rule for target.
readme_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 readme_examples
.PHONY : readme_examples

# fast build rule for target.
readme_examples/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/readme_examples.dir/build.make third_party/cJSON/tests/CMakeFiles/readme_examples.dir/build
.PHONY : readme_examples/fast

#=============================================================================
# Target rules for targets named minify_tests

# Build rule for target.
minify_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minify_tests
.PHONY : minify_tests

# fast build rule for target.
minify_tests/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/tests/CMakeFiles/minify_tests.dir/build.make third_party/cJSON/tests/CMakeFiles/minify_tests.dir/build
.PHONY : minify_tests/fast

#=============================================================================
# Target rules for targets named fuzz_main

# Build rule for target.
fuzz_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fuzz_main
.PHONY : fuzz_main

# fast build rule for target.
fuzz_main/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cJSON/fuzzing/CMakeFiles/fuzz_main.dir/build.make third_party/cJSON/fuzzing/CMakeFiles/fuzz_main.dir/build
.PHONY : fuzz_main/fast

src/aee.o: src/aee.c.o
.PHONY : src/aee.o

# target to build an object file
src/aee.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/aee.c.o
.PHONY : src/aee.c.o

src/aee.i: src/aee.c.i
.PHONY : src/aee.i

# target to preprocess a source file
src/aee.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/aee.c.i
.PHONY : src/aee.c.i

src/aee.s: src/aee.c.s
.PHONY : src/aee.s

# target to generate assembly for a file
src/aee.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/aee.c.s
.PHONY : src/aee.c.s

src/control.o: src/control.c.o
.PHONY : src/control.o

# target to build an object file
src/control.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/control.c.o
.PHONY : src/control.c.o

src/control.i: src/control.c.i
.PHONY : src/control.i

# target to preprocess a source file
src/control.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/control.c.i
.PHONY : src/control.c.i

src/control.s: src/control.c.s
.PHONY : src/control.s

# target to generate assembly for a file
src/control.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/control.c.s
.PHONY : src/control.c.s

src/delete.o: src/delete.c.o
.PHONY : src/delete.o

# target to build an object file
src/delete.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/delete.c.o
.PHONY : src/delete.c.o

src/delete.i: src/delete.c.i
.PHONY : src/delete.i

# target to preprocess a source file
src/delete.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/delete.c.i
.PHONY : src/delete.c.i

src/delete.s: src/delete.c.s
.PHONY : src/delete.s

# target to generate assembly for a file
src/delete.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/delete.c.s
.PHONY : src/delete.c.s

src/file.o: src/file.c.o
.PHONY : src/file.o

# target to build an object file
src/file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/file.c.o
.PHONY : src/file.c.o

src/file.i: src/file.c.i
.PHONY : src/file.i

# target to preprocess a source file
src/file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/file.c.i
.PHONY : src/file.c.i

src/file.s: src/file.c.s
.PHONY : src/file.s

# target to generate assembly for a file
src/file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/file.c.s
.PHONY : src/file.c.s

src/format.o: src/format.c.o
.PHONY : src/format.o

# target to build an object file
src/format.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/format.c.o
.PHONY : src/format.c.o

src/format.i: src/format.c.i
.PHONY : src/format.i

# target to preprocess a source file
src/format.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/format.c.i
.PHONY : src/format.c.i

src/format.s: src/format.c.s
.PHONY : src/format.s

# target to generate assembly for a file
src/format.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/format.c.s
.PHONY : src/format.c.s

src/help.o: src/help.c.o
.PHONY : src/help.o

# target to build an object file
src/help.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/help.c.o
.PHONY : src/help.c.o

src/help.i: src/help.c.i
.PHONY : src/help.i

# target to preprocess a source file
src/help.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/help.c.i
.PHONY : src/help.c.i

src/help.s: src/help.c.s
.PHONY : src/help.s

# target to generate assembly for a file
src/help.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/help.c.s
.PHONY : src/help.c.s

src/highlighting.o: src/highlighting.c.o
.PHONY : src/highlighting.o

# target to build an object file
src/highlighting.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/highlighting.c.o
.PHONY : src/highlighting.c.o

src/highlighting.i: src/highlighting.c.i
.PHONY : src/highlighting.i

# target to preprocess a source file
src/highlighting.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/highlighting.c.i
.PHONY : src/highlighting.c.i

src/highlighting.s: src/highlighting.c.s
.PHONY : src/highlighting.s

# target to generate assembly for a file
src/highlighting.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/highlighting.c.s
.PHONY : src/highlighting.c.s

src/journal.o: src/journal.c.o
.PHONY : src/journal.o

# target to build an object file
src/journal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/journal.c.o
.PHONY : src/journal.c.o

src/journal.i: src/journal.c.i
.PHONY : src/journal.i

# target to preprocess a source file
src/journal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/journal.c.i
.PHONY : src/journal.c.i

src/journal.s: src/journal.c.s
.PHONY : src/journal.s

# target to generate assembly for a file
src/journal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/journal.c.s
.PHONY : src/journal.c.s

src/keys.o: src/keys.c.o
.PHONY : src/keys.o

# target to build an object file
src/keys.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/keys.c.o
.PHONY : src/keys.c.o

src/keys.i: src/keys.c.i
.PHONY : src/keys.i

# target to preprocess a source file
src/keys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/keys.c.i
.PHONY : src/keys.c.i

src/keys.s: src/keys.c.s
.PHONY : src/keys.s

# target to generate assembly for a file
src/keys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/keys.c.s
.PHONY : src/keys.c.s

src/localize.o: src/localize.c.o
.PHONY : src/localize.o

# target to build an object file
src/localize.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/localize.c.o
.PHONY : src/localize.c.o

src/localize.i: src/localize.c.i
.PHONY : src/localize.i

# target to preprocess a source file
src/localize.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/localize.c.i
.PHONY : src/localize.c.i

src/localize.s: src/localize.c.s
.PHONY : src/localize.s

# target to generate assembly for a file
src/localize.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/localize.c.s
.PHONY : src/localize.c.s

src/lsp.o: src/lsp.c.o
.PHONY : src/lsp.o

# target to build an object file
src/lsp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/lsp.c.o
.PHONY : src/lsp.c.o

src/lsp.i: src/lsp.c.i
.PHONY : src/lsp.i

# target to preprocess a source file
src/lsp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/lsp.c.i
.PHONY : src/lsp.c.i

src/lsp.s: src/lsp.c.s
.PHONY : src/lsp.s

# target to generate assembly for a file
src/lsp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/lsp.c.s
.PHONY : src/lsp.c.s

src/mark.o: src/mark.c.o
.PHONY : src/mark.o

# target to build an object file
src/mark.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/mark.c.o
.PHONY : src/mark.c.o

src/mark.i: src/mark.c.i
.PHONY : src/mark.i

# target to preprocess a source file
src/mark.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/mark.c.i
.PHONY : src/mark.c.i

src/mark.s: src/mark.c.s
.PHONY : src/mark.s

# target to generate assembly for a file
src/mark.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/mark.c.s
.PHONY : src/mark.c.s

src/motion.o: src/motion.c.o
.PHONY : src/motion.o

# target to build an object file
src/motion.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/motion.c.o
.PHONY : src/motion.c.o

src/motion.i: src/motion.c.i
.PHONY : src/motion.i

# target to preprocess a source file
src/motion.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/motion.c.i
.PHONY : src/motion.c.i

src/motion.s: src/motion.c.s
.PHONY : src/motion.s

# target to generate assembly for a file
src/motion.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/motion.c.s
.PHONY : src/motion.c.s

src/srch_rep.o: src/srch_rep.c.o
.PHONY : src/srch_rep.o

# target to build an object file
src/srch_rep.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/srch_rep.c.o
.PHONY : src/srch_rep.c.o

src/srch_rep.i: src/srch_rep.c.i
.PHONY : src/srch_rep.i

# target to preprocess a source file
src/srch_rep.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/srch_rep.c.i
.PHONY : src/srch_rep.c.i

src/srch_rep.s: src/srch_rep.c.s
.PHONY : src/srch_rep.s

# target to generate assembly for a file
src/srch_rep.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/srch_rep.c.s
.PHONY : src/srch_rep.c.s

src/windows.o: src/windows.c.o
.PHONY : src/windows.o

# target to build an object file
src/windows.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/windows.c.o
.PHONY : src/windows.c.o

src/windows.i: src/windows.c.i
.PHONY : src/windows.i

# target to preprocess a source file
src/windows.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/windows.c.i
.PHONY : src/windows.c.i

src/windows.s: src/windows.c.s
.PHONY : src/windows.s

# target to generate assembly for a file
src/windows.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aee.dir/build.make CMakeFiles/aee.dir/src/windows.c.s
.PHONY : src/windows.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... check"
	@echo "... uninstall"
	@echo "... aee"
	@echo "... cJSON_test"
	@echo "... cjson"
	@echo "... cjson_add"
	@echo "... compare_tests"
	@echo "... fuzz_main"
	@echo "... minify_tests"
	@echo "... misc_tests"
	@echo "... parse_array"
	@echo "... parse_examples"
	@echo "... parse_hex4"
	@echo "... parse_number"
	@echo "... parse_object"
	@echo "... parse_string"
	@echo "... parse_value"
	@echo "... parse_with_opts"
	@echo "... print_array"
	@echo "... print_number"
	@echo "... print_object"
	@echo "... print_string"
	@echo "... print_value"
	@echo "... readme_examples"
	@echo "... unity"
	@echo "... src/aee.o"
	@echo "... src/aee.i"
	@echo "... src/aee.s"
	@echo "... src/control.o"
	@echo "... src/control.i"
	@echo "... src/control.s"
	@echo "... src/delete.o"
	@echo "... src/delete.i"
	@echo "... src/delete.s"
	@echo "... src/file.o"
	@echo "... src/file.i"
	@echo "... src/file.s"
	@echo "... src/format.o"
	@echo "... src/format.i"
	@echo "... src/format.s"
	@echo "... src/help.o"
	@echo "... src/help.i"
	@echo "... src/help.s"
	@echo "... src/highlighting.o"
	@echo "... src/highlighting.i"
	@echo "... src/highlighting.s"
	@echo "... src/journal.o"
	@echo "... src/journal.i"
	@echo "... src/journal.s"
	@echo "... src/keys.o"
	@echo "... src/keys.i"
	@echo "... src/keys.s"
	@echo "... src/localize.o"
	@echo "... src/localize.i"
	@echo "... src/localize.s"
	@echo "... src/lsp.o"
	@echo "... src/lsp.i"
	@echo "... src/lsp.s"
	@echo "... src/mark.o"
	@echo "... src/mark.i"
	@echo "... src/mark.s"
	@echo "... src/motion.o"
	@echo "... src/motion.i"
	@echo "... src/motion.s"
	@echo "... src/srch_rep.o"
	@echo "... src/srch_rep.i"
	@echo "... src/srch_rep.s"
	@echo "... src/windows.o"
	@echo "... src/windows.i"
	@echo "... src/windows.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

