name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name make prefix
      run: mkdir -p ./usr/bin ./usr/share/man/man1/
    - name: make
      run: make CFLAGS="-static"
    - name: make install
      run: DESTDIR=. PREFIX=/usr/ make install
    - name: package
      run: tar czf aee-14.1.tar.gz ./usr/
    - name: make uninstall
      run: make uninstall
    - name: make clean
      run: make clean
